# Generated by Django 3.0.8 on 2020-07-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statictics",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=25, default=0, max_digits=50)),
                ("alias", models.CharField(default="mywallet", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=25, default=0, max_digits=50)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "destination_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="destination_wallet", to="api.Wallet"
                    ),
                ),
                (
                    "origin_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="origin_wallet", to="api.Wallet"
                    ),
                ),
            ],
        ),
    ]
