# Generated by Django 3.0.8 on 2020-07-28 15:41

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="wallet", name="address", field=models.UUIDField(default=uuid.uuid4),),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=25, default=Decimal("1.0"), max_digits=50),
        ),
    ]
