# Generated by Django 3.0.8 on 2020-07-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200728_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=25, default=0, max_digits=50),
        ),
        migrations.AddField(model_name="transaction", name="code", field=models.CharField(blank=True, max_length=50),),
        migrations.AddField(
            model_name="transaction",
            name="destination_wallet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_wallet",
                to="api.Wallet",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="origin_wallet",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="origin_wallet", to="api.Wallet"
            ),
        ),
        migrations.DeleteModel(name="Transfer",),
    ]
