# Generated by Django 3.0.8 on 2020-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200728_1646"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="destination_wallet",),
        migrations.RemoveField(model_name="transaction", name="origin_wallet",),
        migrations.AddField(
            model_name="transaction", name="destination_address", field=models.UUIDField(default=None),
        ),
        migrations.AddField(model_name="transaction", name="origin_address", field=models.UUIDField(default=None),),
    ]
