# Generated by Django 3.0.8 on 2020-07-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200728_1727"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, verbose_name="Paxful")),
                ("profit", models.DecimalField(decimal_places=25, default=0, max_digits=50)),
                ("profit_to_USD", models.DecimalField(decimal_places=10, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="statictics",
            name="transactions",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="api.Transaction"),
        ),
        migrations.AddField(
            model_name="statictics",
            name="platform",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="api.Platform"),
        ),
    ]
