# Generated by Django 3.0.8 on 2020-07-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200728_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statictics",
            name="transactions",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Transaction"
            ),
        ),
    ]
