# Generated by Django 3.0.8 on 2020-07-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20200728_2112"),
    ]

    operations = [
        migrations.DeleteModel(name="Statictics",),
    ]
